export { default as ReportScreen } from './ReportScreen'
export { default as DNDScreen } from './DNDScreen'
export { default as SuggestionsScreen } from './SuggestionsScreen'
export { default as LandingScreen } from './LandingScreen'
export { default as ClassScreen } from './ClassScreen'
export { default as MarkScreen } from './MarkScreen'